//! Match enum variants without requiring their payload types to implement
//! a common trait.
//!
//! `match-variants` generates a small helper macro for an enum and uses it
//! to apply the same expression to each data-carrying variant.
//!
//! # Example
//!
//! ```
//! use match_variants::{match_variants, MatchVariants};
//!
//! struct Foo(f64);
//! struct Bar(f64);
//!
//! impl Foo {
//!     fn value(self) -> f64 {
//!         self.0
//!     }
//! }
//!
//! impl Bar {
//!     fn value(self) -> f64 {
//!         self.0 * 2.0
//!     }
//! }
//!
//! #[derive(MatchVariants)]
//! enum Value {
//!     Foo(Foo),
//!     Bar(Bar),
//! }
//!
//! fn value(value: Value) -> f64 {
//!     match_variants!(Value, value, (x), {
//!         x.value()
//!     })
//! }
//!
//! assert_eq!(value(Value::Foo(Foo(10.0))), 10.0);
//! assert_eq!(value(Value::Bar(Bar(10.0))), 20.0);
//! ```

use proc_macro::TokenStream;

mod derive;
mod import_match_variants;
mod match_variants;

/// Generates the helper macro required by [`match_variants!`].
///
/// `MatchVariants` can be derived for enums whose variants contain data.
///
/// All variants must use the same variant shape:
///
/// - all tuple variants, or
/// - all struct-like variants.
///
/// Unit variants and mixing tuple and struct-like variants are not supported.
///
/// # Example
///
/// ```
/// use match_variants::MatchVariants;
///
/// struct Foo;
/// struct Bar;
///
/// #[derive(MatchVariants)]
/// enum Value {
///     Foo(Foo),
///     Bar(Bar),
/// }
/// ```
///
/// For an enum named `Value`, the derive generates a helper macro named
/// `match_variants_for_Value`.
#[proc_macro_derive(MatchVariants, attributes(variant_type))]
pub fn derive_match_variants(input: TokenStream) -> TokenStream {
    derive::expand(input)
}

/// Applies the same expression to every variant of an enum.
///
/// The payload bindings are concrete in each generated match arm. This means
/// different variants may contain unrelated types as long as the supplied
/// expression is valid for each type and all arms produce compatible results.
///
/// # Tuple variants
///
/// ```
/// use match_variants::{match_variants, MatchVariants};
///
/// struct Foo(i32);
/// struct Bar(i32);
///
/// impl Foo {
///     fn value(self) -> i32 {
///         self.0
///     }
/// }
///
/// impl Bar {
///     fn value(self) -> i32 {
///         self.0
///     }
/// }
///
/// #[derive(MatchVariants)]
/// enum Value {
///     Foo(Foo),
///     Bar(Bar),
/// }
///
/// let value = Value::Foo(Foo(42));
///
/// let result = match_variants!(Value, value, (x), {
///     x.value()
/// });
///
/// assert_eq!(result, 42);
/// ```
///
/// # Struct-like variants
///
/// ```
/// use match_variants::{match_variants, MatchVariants};
///
/// struct Foo(i32);
/// struct Bar(i32);
///
/// impl Foo {
///     fn value(self) -> i32 {
///         self.0
///     }
/// }
///
/// impl Bar {
///     fn value(self) -> i32 {
///         self.0
///     }
/// }
///
/// #[derive(MatchVariants)]
/// enum Value {
///     Foo { value: Foo },
///     Bar { value: Bar },
/// }
///
/// let value = Value::Bar { value: Bar(42) };
///
/// let result = match_variants!(Value, value, { value: x }, {
///     x.value()
/// });
///
/// assert_eq!(result, 42);
/// ```
///
/// When matching an enum from another module, use
/// [`import_match_variants!`] to bring its generated helper macro into scope.
#[proc_macro]
pub fn match_variants(input: TokenStream) -> TokenStream {
    match_variants::expand(input)
}

/// Imports the helper macros generated by [`MatchVariants`].
///
/// This is needed when enums derived with [`MatchVariants`] are used from
/// another module.
///
/// # Example
///
/// ```
/// mod domain {
///     use match_variants::MatchVariants;
///
///     pub struct Foo(pub i32);
///     pub struct Bar(pub i32);
///
///     impl Foo {
///         pub fn value(self) -> i32 {
///             self.0
///         }
///     }
///
///     impl Bar {
///         pub fn value(self) -> i32 {
///             self.0
///         }
///     }
///
///     #[derive(MatchVariants)]
///     pub enum Value {
///         Foo(Foo),
///         Bar(Bar),
///     }
/// }
///
/// mod application {
///     use match_variants::{import_match_variants, match_variants};
///
///     import_match_variants!(
///         crate::domain::{
///             Value,
///         }
///     );
///
///     pub fn value(value: crate::domain::Value) -> i32 {
///         match_variants!(crate::domain::Value, value, (x), {
///             x.value()
///         })
///     }
/// }
///
/// fn main() {
///     let value = domain::Value::Foo(domain::Foo(42));
///
///     assert_eq!(application::value(value), 42);
/// }
/// ```
///
/// Multiple enums from the same module can be imported at once:
///
/// ```text
/// import_match_variants!(
///     crate::domain::{
///         FooValue,
///         BarValue,
///         BazValue,
///     }
/// );
/// ```
#[proc_macro]
pub fn import_match_variants(input: TokenStream) -> TokenStream {
    import_match_variants::expand(input)
}
